name: cinemax-admin-panel

on:
  push:
    branches: [ main ]

env:
  PYTHONUNBUFFERED: 1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    services:
      postgres:
        image: postgres:14.5-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: cinemax_database
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Install dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
          pip install wemake-python-styleguide flake8-html mypy lxml
      - name: Lint with flake8
        run: flake8 backend --format=html --htmldir=flake8
      - name: Lint with mypy
        run: mypy backend --html-report=mypy 
      - name: Run migrations
        run: psql -f infra/data/cinemax_database.sql postgresql://postgres:postgres@localhost:5432/cinemax_database
      - name: Run server
        run: |
          cd backend/src
          python manage.py migrate --fake movies 0001_initial
          python manage.py migrate
          nohup python manage.py runserver &
      - name: API tests with Postman
        run: |
          cd tests
          newman run src/cinemax_API.postman_collection.json -r htmlextra,cli --reporter-htmlextra-export="../postman/report.html"
      - name: Stop server
        run: kill $(ps aux | grep python | grep manage.py | awk '{print $2}')
      - name: Output results
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: |
            postman/
            flake8/
            mypy/
  
  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Backend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: backend
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/django_admin_panel:${{ vars.TAG }}
            ${{ secrets.DOCKER_USERNAME }}/django_admin_panel:latest

  send_message:
    name: Send message
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            В репозитории ${{ github.repository }} выполнен коммит:
            Автор: ${{ github.event.commits[0].author.name }}
            Сообщение: ${{ github.event.commits[0].message }}
            Ссылка: https://github.com/${{ github.repository }}/commit/${{github.sha}}
